(dp1
S'output'
p2
S"<type 'exceptions.TypeError'> 'module' object is not callable"
p3
sS'layer'
p4
S'/home/hai/Projects/web2py/applications/FinalProject/controllers/randomGameGen.py'
p5
sS'code'
p6
S'import random\ndef index():\n\tnumber = random()\n\n\treturn dict(number=number)\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/hai/Projects/web2py/gluon/restricted.py", line 224, in restricted\n    exec ccode in environment\n  File "/home/hai/Projects/web2py/applications/FinalProject/controllers/randomGameGen.py", line 6, in <module>\n  File "/home/hai/Projects/web2py/gluon/globals.py", line 392, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/hai/Projects/web2py/applications/FinalProject/controllers/randomGameGen.py", line 3, in index\n    number = random()\nTypeError: \'module\' object is not callable\n'
p11
s.